export default restaurants = [
    {
      info: {
        id: '613166',
        name: 'Sree Saravana Bhavan',
        cloudinaryImageId: 'nvxbtcmc2eqruhljkjxo',
        locality: 'New Market Street',
        areaName: 'South Tirupur',
        costForTwo: '₹250 for two',
        cuisines: ['South Indian', 'Indian', 'Beverages'],
        avgRating: 4.5,
        veg: true,
        parentId: '193221',
        avgRatingString: '4.5',
        totalRatingsString: '500+',
        sla: {
          deliveryTime: 32,
          lastMileTravel: 5.7,
          serviceability: 'SERVICEABLE',
          slaString: '30-35 mins',
          lastMileTravelString: '5.7 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 21:30:00', opened: true },
        badges: {},
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: {
          header: '₹50 OFF',
          subHeader: 'ABOVE ₹199',
          discountTag: 'FLAT DEAL',
        },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/sree-saravana-bhavan-new-market-street-south-tirupur-tirupur-613166',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '484533',
        name: 'Annapoorna',
        cloudinaryImageId: 'h73wp0kk8dwo175bhfb1',
        locality: 'Laxmi Nagar',
        areaName: 'Tiruppur',
        costForTwo: '₹200 for two',
        cuisines: ['South Indian', 'Chinese'],
        avgRating: 4.3,
        veg: true,
        parentId: '3791',
        avgRatingString: '4.3',
        totalRatingsString: '10K+',
        sla: {
          deliveryTime: 28,
          lastMileTravel: 4.9,
          serviceability: 'SERVICEABLE',
          slaString: '25-30 mins',
          lastMileTravelString: '4.9 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 22:50:00', opened: true },
        badges: {},
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: {
          header: '₹50 OFF',
          subHeader: 'ABOVE ₹199',
          discountTag: 'FLAT DEAL',
        },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/annapoorna-laxmi-nagar-tiruppur-tirupur-484533',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '72653',
        name: 'A2B - Adyar Ananda Bhavan',
        cloudinaryImageId: 'ixegdbfakwwpbpgqrnyp',
        locality: 'PN Road',
        areaName: 'Kumar Nagar',
        costForTwo: '₹300 for two',
        cuisines: ['South Indian', 'North Indian', 'Sweets', 'Chinese'],
        avgRating: 4.5,
        veg: true,
        parentId: '22',
        avgRatingString: '4.5',
        totalRatingsString: '10K+',
        sla: {
          deliveryTime: 36,
          lastMileTravel: 3,
          serviceability: 'SERVICEABLE',
          slaString: '35-40 mins',
          lastMileTravelString: '3.0 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 22:45:00', opened: true },
        badges: {
          imageBadges: [
            {
              imageId: 'v1695133679/badges/Pure_Veg111.png',
              description: 'pureveg',
            },
          ],
        },
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: 'pureveg',
                    imageId: 'v1695133679/badges/Pure_Veg111.png',
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: { header: '20% OFF', subHeader: 'UPTO ₹50' },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/a2b-adyar-ananda-bhavan-pn-road-kumar-nagar-tirupur-72653',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '619333',
        name: 'Cheesecakes By CakeZone',
        cloudinaryImageId: '76d5f4055f9d5796bc7b72dfba8bd92b',
        locality: 'Kavery Street',
        areaName: 'Laxmi Nagar',
        costForTwo: '₹200 for two',
        cuisines: ['Bakery', 'Desserts'],
        avgRating: 4.3,
        veg: true,
        parentId: '348057',
        avgRatingString: '4.3',
        totalRatingsString: '100+',
        sla: {
          deliveryTime: 35,
          lastMileTravel: 4.8,
          serviceability: 'SERVICEABLE',
          slaString: '30-35 mins',
          lastMileTravelString: '4.8 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-19 01:00:00', opened: true },
        badges: {},
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: '60% OFF', subHeader: 'UPTO ₹120' },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/cheesecakes-by-cakezone-kavery-street-laxmi-nagar-tirupur-619333',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '619273',
        name: 'CakeZone Patisserie',
        cloudinaryImageId: 'dd5886c5e8b7943cce6b751825380a45',
        locality: 'Kavery Street',
        areaName: 'Laxmi Nagar',
        costForTwo: '₹200 for two',
        cuisines: ['Bakery', 'Desserts', 'Sweets', 'Ice Cream'],
        avgRating: 4.3,
        parentId: '7003',
        avgRatingString: '4.3',
        totalRatingsString: '1K+',
        sla: {
          deliveryTime: 36,
          lastMileTravel: 4.8,
          serviceability: 'SERVICEABLE',
          slaString: '35-40 mins',
          lastMileTravelString: '4.8 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-19 01:00:00', opened: true },
        badges: {},
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: '60% OFF', subHeader: 'UPTO ₹120' },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/cakezone-patisserie-kavery-street-laxmi-nagar-tirupur-619273',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '227089',
        name: 'Sweet Truth - Cake and Desserts',
        cloudinaryImageId: '78408969d316991befba0a6eca303e1c',
        locality: 'Valipalayam',
        areaName: 'Tiruppur',
        costForTwo: '₹450 for two',
        cuisines: ['Snacks', 'Bakery', 'Desserts', 'Beverages'],
        avgRating: 4.4,
        parentId: '4444',
        avgRatingString: '4.4',
        totalRatingsString: '1K+',
        sla: {
          deliveryTime: 33,
          lastMileTravel: 5,
          serviceability: 'SERVICEABLE',
          slaString: '30-35 mins',
          lastMileTravelString: '5.0 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 23:59:00', opened: true },
        badges: {},
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: '40% OFF', subHeader: 'UPTO ₹80' },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/sweet-truth-cake-and-desserts-valipalayam-tiruppur-tirupur-227089',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '486471',
        name: 'Tirupur Sree Annapoorna',
        cloudinaryImageId: 's5qg9nwmh747yquobu5s',
        locality: 'Rayan Kovil',
        areaName: 'Avinashi',
        costForTwo: '₹200 for two',
        cuisines: ['South Indian', 'North Indian', 'Beverages'],
        avgRating: 4.3,
        veg: true,
        parentId: '291053',
        avgRatingString: '4.3',
        totalRatingsString: '1K+',
        sla: {
          deliveryTime: 40,
          lastMileTravel: 11.5,
          serviceability: 'SERVICEABLE',
          slaString: '40-45 mins',
          lastMileTravelString: '11.5 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 21:00:00', opened: true },
        badges: {},
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: {
          header: '₹125 OFF',
          subHeader: 'ABOVE ₹199',
          discountTag: 'FLAT DEAL',
        },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/tirupur-sree-annapoorna-rayan-kovil-avinashi-tirupur-486471',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '165932',
        name: 'Fresh & Fresh',
        cloudinaryImageId: 't15xt9yeekgcodhdq0av',
        locality: 'Thiruneelakandapuram',
        areaName: 'Valayankadu',
        costForTwo: '₹200 for two',
        cuisines: ['South Indian', 'Indian'],
        avgRating: 4.6,
        veg: true,
        parentId: '83537',
        avgRatingString: '4.6',
        totalRatingsString: '1K+',
        sla: {
          deliveryTime: 34,
          lastMileTravel: 3.9,
          serviceability: 'SERVICEABLE',
          slaString: '30-35 mins',
          lastMileTravelString: '3.9 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 10:00:00', opened: true },
        badges: {
          imageBadges: [
            {
              imageId: 'v1695133679/badges/Pure_Veg111.png',
              description: 'pureveg',
            },
          ],
        },
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: 'F',
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: 'pureveg',
                    imageId: 'v1695133679/badges/Pure_Veg111.png',
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/fresh-and-fresh-thiruneelakandapuram-valayankadu-tirupur-165932',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '619276',
        name: 'The Dessert Heaven - Pure Veg',
        cloudinaryImageId: 'bca418d5554239d48ac1f8ba84a42d79',
        locality: 'Cauvery Street',
        areaName: 'Laxmi Nagar',
        costForTwo: '₹200 for two',
        cuisines: ['Bakery', 'Desserts', 'Sweets', 'Ice Cream'],
        avgRating: 4.4,
        veg: true,
        parentId: '350292',
        avgRatingString: '4.4',
        totalRatingsString: '100+',
        sla: {
          deliveryTime: 39,
          lastMileTravel: 4.8,
          serviceability: 'SERVICEABLE',
          slaString: '35-40 mins',
          lastMileTravelString: '4.8 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-19 01:00:00', opened: true },
        badges: {},
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: '60% OFF', subHeader: 'UPTO ₹120' },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/the-dessert-heaven-pure-veg-cauvery-street-laxmi-nagar-tirupur-619276',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '693273',
        name: 'Ovenfresh Cakes And Desserts',
        cloudinaryImageId: '02ff1078bf785ceb3616ebe1cd02ee38',
        locality: 'Kavery Street',
        areaName: 'North Tirupur',
        costForTwo: '₹200 for two',
        cuisines: [
          'Bakery',
          'Desserts',
          'Beverages',
          'Ice Cream',
          'Sweets',
          'Juices',
          'Bengali',
          'Pizzas',
        ],
        avgRating: 4.4,
        parentId: '1372',
        avgRatingString: '4.4',
        totalRatingsString: '100+',
        sla: {
          deliveryTime: 37,
          lastMileTravel: 4.8,
          serviceability: 'SERVICEABLE',
          slaString: '35-40 mins',
          lastMileTravelString: '4.8 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-19 01:00:00', opened: true },
        badges: {},
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: '60% OFF', subHeader: 'UPTO ₹120' },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/ovenfresh-cakes-and-desserts-kavery-street-north-tirupur-tirupur-693273',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '263836',
        name: 'Pure Veg Meals by Lunchbox',
        cloudinaryImageId: 'pjzm6jh5cpvjhyogmtdv',
        locality: 'Valipalayam',
        areaName: 'Tiruppur',
        costForTwo: '₹200 for two',
        cuisines: ['Biryani', 'North Indian', 'Desserts', 'Beverages'],
        avgRating: 4.3,
        veg: true,
        parentId: '21938',
        avgRatingString: '4.3',
        totalRatingsString: '100+',
        sla: {
          deliveryTime: 37,
          lastMileTravel: 5,
          serviceability: 'SERVICEABLE',
          slaString: '35-40 mins',
          lastMileTravelString: '5.0 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 23:59:00', opened: true },
        badges: {
          imageBadges: [
            {
              imageId: 'v1695133679/badges/Pure_Veg111.png',
              description: 'pureveg',
            },
          ],
        },
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: 'pureveg',
                    imageId: 'v1695133679/badges/Pure_Veg111.png',
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: { header: '40% OFF', subHeader: 'UPTO ₹80' },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/pure-veg-meals-by-lunchbox-valipalayam-tiruppur-tirupur-263836',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '670071',
        name: 'Vanakkam Punjaab',
        cloudinaryImageId: '2a302f105ec371d077438b301b23ccf8',
        locality: 'Court Street',
        areaName: 'Central Tirupur',
        costForTwo: '₹500 for two',
        cuisines: ['Punjabi', 'Indian'],
        avgRating: 4.3,
        veg: true,
        parentId: '401642',
        avgRatingString: '4.3',
        totalRatingsString: '1K+',
        sla: {
          deliveryTime: 39,
          lastMileTravel: 5.5,
          serviceability: 'SERVICEABLE',
          slaString: '35-40 mins',
          lastMileTravelString: '5.5 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 11:00:00', opened: true },
        badges: {
          imageBadges: [
            {
              imageId: 'v1695133679/badges/Pure_Veg111.png',
              description: 'pureveg',
            },
          ],
        },
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: 'pureveg',
                    imageId: 'v1695133679/badges/Pure_Veg111.png',
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: '₹125 OFF',
          subHeader: 'ABOVE ₹199',
          discountTag: 'FLAT DEAL',
        },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/vanakkam-punjaab-court-street-central-tirupur-tirupur-670071',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '298830',
        name: 'Vasantha Mess',
        cloudinaryImageId: 'n52uxzjuu8c1vaprr6im',
        locality: 'Veerapandi',
        areaName: 'Tiruppur',
        costForTwo: '₹200 for two',
        cuisines: ['South Indian', 'Indian'],
        avgRating: 4.4,
        parentId: '471675',
        avgRatingString: '4.4',
        totalRatingsString: '1K+',
        sla: {
          deliveryTime: 36,
          lastMileTravel: 9.7,
          serviceability: 'SERVICEABLE',
          slaString: '35-40 mins',
          lastMileTravelString: '9.7 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 22:30:00', opened: true },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/vasantha-mess-veerapandi-tiruppur-tirupur-298830',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '279283',
        name: 'Sri Amman Relax',
        cloudinaryImageId: 'usa1dngt5pfzpwfte1tb',
        locality: 'Valliammai Nagar',
        areaName: 'Tiruppur',
        costForTwo: '₹300 for two',
        cuisines: ['South Indian'],
        avgRating: 4.3,
        parentId: '193338',
        avgRatingString: '4.3',
        totalRatingsString: '500+',
        sla: {
          deliveryTime: 39,
          lastMileTravel: 8.3,
          serviceability: 'SERVICEABLE',
          slaString: '35-40 mins',
          lastMileTravelString: '8.3 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 22:30:00', opened: true },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/sri-amman-relax-valliammai-nagar-tiruppur-tirupur-279283',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '659426',
        name: 'Hotel Ramanas (Veg)',
        cloudinaryImageId: 'bf169e25ae326ea490eb1b6fbcfaeac4',
        locality: 'Valipalayam',
        areaName: 'Tiruppur',
        costForTwo: '₹200 for two',
        cuisines: ['South Indian', 'Beverages', 'Juices'],
        avgRating: 4.6,
        veg: true,
        parentId: '396042',
        avgRatingString: '4.6',
        totalRatingsString: '100+',
        sla: {
          deliveryTime: 33,
          lastMileTravel: 7.5,
          serviceability: 'SERVICEABLE',
          slaString: '30-35 mins',
          lastMileTravelString: '7.5 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 22:00:00', opened: true },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/hotel-ramanas-veg-valipalayam-tiruppur-tirupur-659426',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '723280',
        name: 'Cakes By Chocolates',
        cloudinaryImageId: '9f96c819e63f0af05f915dc8d46f3de4',
        locality: 'Pudur',
        areaName: 'North Tirupur',
        costForTwo: '₹400 for two',
        cuisines: ['Bakery'],
        avgRating: 4.6,
        veg: true,
        parentId: '18083',
        avgRatingString: '4.6',
        totalRatingsString: '20+',
        sla: {
          deliveryTime: 24,
          lastMileTravel: 3,
          serviceability: 'SERVICEABLE',
          slaString: '20-25 mins',
          lastMileTravelString: '3.0 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 22:00:00', opened: true },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/cakes-by-chocolates-pudur-north-tirupur-tirupur-723280',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '211944',
        name: 'Sri Meenatchisundaram chettinadu mess',
        cloudinaryImageId: 'gauqanu1aqsjhf1wwxu2',
        locality: 'PN Road',
        areaName: 'PN Road',
        costForTwo: '₹200 for two',
        cuisines: ['Chinese', 'South Indian', 'Indian'],
        avgRating: 4,
        parentId: '8733',
        avgRatingString: '4.0',
        totalRatingsString: '1K+',
        sla: {
          deliveryTime: 29,
          lastMileTravel: 2.7,
          serviceability: 'SERVICEABLE',
          slaString: '25-30 mins',
          lastMileTravelString: '2.7 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 23:00:00', opened: true },
        badges: {},
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: {
          header: '₹125 OFF',
          subHeader: 'ABOVE ₹249',
          discountTag: 'FLAT DEAL',
        },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/sri-meenatchisundaram-chettinadu-mess-pn-road-tirupur-211944',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '299436',
        name: 'Sami Mess',
        cloudinaryImageId: 'wbyb8uvqsf7uca0bspkr',
        locality: 'Valliammai Nagar',
        areaName: 'DHARAPURAM MAIN ROAD',
        costForTwo: '₹200 for two',
        cuisines: ['South Indian', 'Grill', 'Continental'],
        avgRating: 4,
        parentId: '176497',
        avgRatingString: '4.0',
        totalRatingsString: '100+',
        sla: {
          deliveryTime: 38,
          lastMileTravel: 8.8,
          serviceability: 'SERVICEABLE',
          slaString: '35-40 mins',
          lastMileTravelString: '8.8 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-19 00:00:00', opened: true },
        badges: {},
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: '10% OFF', subHeader: 'UPTO ₹40' },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/sami-mess-valliammai-nagar-dharapuram-main-road-tirupur-299436',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '566419',
        name: "Faasos' Signature Wraps & Rolls",
        cloudinaryImageId: 'c583ca6ce40b426797a78ae2ac91f2ec',
        locality: 'RAILWAY FEEDER Road',
        areaName: 'Valipalayam',
        costForTwo: '₹350 for two',
        cuisines: [
          'Fast Food',
          'Snacks',
          'North Indian',
          'Desserts',
          'Beverages',
        ],
        avgRating: 3.7,
        parentId: '340366',
        avgRatingString: '3.7',
        totalRatingsString: '10+',
        sla: {
          deliveryTime: 40,
          lastMileTravel: 5,
          serviceability: 'SERVICEABLE',
          slaString: '40-45 mins',
          lastMileTravelString: '5.0 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 23:59:00', opened: true },
        badges: {},
        isOpen: true,
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        aggregatedDiscountInfoV3: { header: '50% OFF', subHeader: 'UPTO ₹100' },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/faasos-signature-wraps-and-rolls-railway-feeder-road-valipalayam-tirupur-566419',
        type: 'WEBLINK',
      },
    },
    {
      info: {
        id: '760203',
        name: 'Sree Annapoorna',
        cloudinaryImageId: '57ad35c7a51bfc3df3703fef028ad071',
        locality: 'Near Covai Byepass',
        areaName: 'Avinashi',
        costForTwo: '₹250 for two',
        cuisines: ['Indian', 'South Indian', 'Tandoor', 'Chinese'],
        avgRating: 4.4,
        veg: true,
        parentId: '4732',
        avgRatingString: '4.4',
        totalRatingsString: '100+',
        sla: {
          deliveryTime: 37,
          lastMileTravel: 9.9,
          serviceability: 'SERVICEABLE',
          slaString: '35-40 mins',
          lastMileTravelString: '9.9 km',
          iconType: 'ICON_TYPE_EMPTY',
        },
        availability: { nextCloseTime: '2024-02-18 22:25:00', opened: true },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: 'F',
        badgesV2: {
          entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
        },
        differentiatedUi: {
          displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
          differentiatedUiMediaDetails: {
            mediaType: 'ADS_MEDIA_ENUM_IMAGE',
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
        isNewlyOnboarded: true,
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: 'https://www.swiggy.com/restaurants/sree-annapoorna-near-covai-byepass-avinashi-tirupur-760203',
        type: 'WEBLINK',
      },
    },
  ];
  